### ISSUE TITLE
Size limit

### ISSUE THREAD

**Issue by llermaly** [BosNaufal/react-file-base64#5]
Hello and thanks for this nice plugin

Could you explain the way to limit file size on upload? Thanks!!

**Comment by BosNaufal** [comment]
Hi @llermaly, it's a nice Idea. But you can do the validation outside the component. It means you can do it in the callback onDone. Just check the file size then limit it. :grin: :+1:

**Comment by omarqra** [comment]
ok how to do it in callback ??
